// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARHOkiuJRLRFFONu-dOgKQE_lBIEY99aE',
    appId: '1:881971598462:web:f270f5bccb964ad897342f',
    messagingSenderId: '881971598462',
    projectId: 'beauty-fier',
    authDomain: 'beauty-fier.firebaseapp.com',
    storageBucket: 'beauty-fier.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvcOdCeJxuQRhNi9mYEUoZK2YhvC2xO3g',
    appId: '1:881971598462:android:563bc9e3ca20c13097342f',
    messagingSenderId: '881971598462',
    projectId: 'beauty-fier',
    storageBucket: 'beauty-fier.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBICRRvyPsi59r80H-wxVI-dQhhJcpnAEY',
    appId: '1:881971598462:ios:ff9ed720c674754497342f',
    messagingSenderId: '881971598462',
    projectId: 'beauty-fier',
    storageBucket: 'beauty-fier.appspot.com',
    androidClientId: '881971598462-0323v0981faqs13fietvogf3md6lq3mr.apps.googleusercontent.com',
    iosClientId: '881971598462-p4jc7v2tmkvj90ui955poer1f2ehjp6r.apps.googleusercontent.com',
    iosBundleId: 'com.example.doctorAppUpdated',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBICRRvyPsi59r80H-wxVI-dQhhJcpnAEY',
    appId: '1:881971598462:ios:27eeecf3f92122ac97342f',
    messagingSenderId: '881971598462',
    projectId: 'beauty-fier',
    storageBucket: 'beauty-fier.appspot.com',
    androidClientId: '881971598462-0323v0981faqs13fietvogf3md6lq3mr.apps.googleusercontent.com',
    iosClientId: '881971598462-4o75ptve4v2rfore2j9lvvrmb7dc63t9.apps.googleusercontent.com',
    iosBundleId: 'com.example.doctorAppUpdated.RunnerTests',
  );
}
